name: Release Pending
description: GitHub Action for versioned releases 📦
author: Kieron Wilkinson

branding:
  icon: package
  color: black

inputs:
  default-tag:
    description: What tag to use for the release if no prior release is found.
    required: true
    default: v0.0.0

outputs:
  action:
    description: The action taken by the release process.
  version:
    description: The inferred or determined version for the release.
  release-id:
    description: The numeric identifier of the created or updated release.

runs:
  using: node24
  main: dist/index.js
